name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install --openssl-legacy-provider
        npm run build --openssl-legacy-provider
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
